"use server";

import { revalidatePath } from "next/cache";

import { createClient } from "@/lib/supabase/server";
import type { RepairCategory, UrgencyLevel } from "@/types/database";

const CATEGORIES: RepairCategory[] = ["electrical", "plumbing", "building_structure", "furniture_equipment", "environment_grounds", "other"];
const URGENCIES: UrgencyLevel[] = ["low", "medium", "high", "emergency"];

export type ReportResult = { ok: boolean; message: string };

export async function createRepairTicket(_prev: ReportResult | null, formData: FormData): Promise<ReportResult> {
  const str = (k: string) => String(formData.get(k) ?? "").trim();
  const title = str("title");
  const description = str("description");
  const building = str("location_building");
  const room = str("location_room");
  const category = str("category") as RepairCategory;
  const urgency = str("urgency") as UrgencyLevel;

  if (!title || !description || !building) {
    return { ok: false, message: "กรุณากรอกหัวข้อ รายละเอียด และอาคาร/สถานที่ให้ครบ" };
  }
  if (!CATEGORIES.includes(category) || !URGENCIES.includes(urgency)) {
    return { ok: false, message: "ข้อมูลหมวดหมู่หรือความเร่งด่วนไม่ถูกต้อง" };
  }

  if (!process.env.NEXT_PUBLIC_SUPABASE_URL || !process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY) {
    return { ok: true, message: "โหมดสาธิต: ยังไม่ได้ตั้งค่า Supabase จึงไม่ได้บันทึกข้อมูลจริง" };
  }

  const supabase = await createClient();
  const { data: auth } = await supabase.auth.getUser();
  if (!auth.user) {
    return { ok: true, message: "โหมดสาธิต: ยังไม่ได้เข้าสู่ระบบ จึงไม่ได้บันทึกข้อมูลจริง" };
  }

  // ticket_number is generated by the DB trigger (REQ-YYYYMM-XXXX).
  const { error } = await supabase.from("repair_tickets").insert({
    reporter_id: auth.user.id,
    title,
    description,
    category,
    urgency,
    location_building: building,
    location_room: room || null,
    ticket_number: "",
  });
  if (error) return { ok: false, message: `บันทึกไม่สำเร็จ: ${error.message}` };

  revalidatePath("/");
  return { ok: true, message: "ส่งเรื่องแจ้งซ่อมเรียบร้อยแล้ว" };
}
