"use server";

import { revalidatePath } from "next/cache";

import { createClient } from "@/lib/supabase/server";
import type { UrgencyLevel } from "@/types/database";

const URGENCIES: UrgencyLevel[] = ["low", "medium", "high", "emergency"];

export type ReportResult = { ok: boolean; message: string };

export async function createRepairTicket(_prev: ReportResult | null, formData: FormData): Promise<ReportResult> {
  const str = (k: string) => String(formData.get(k) ?? "").trim();
  const title = str("title");
  const description = str("description");
  const buildingId = str("building_id");
  const locationDetail = str("location_detail");
  const urgency = str("urgency") as UrgencyLevel;
  const imagePaths = formData.getAll("image_paths").map(String);

  if (!title || !description || !buildingId) {
    return { ok: false, message: "กรุณากรอกหัวข้อ รายละเอียด และเลือกอาคารให้ครบ" };
  }
  if (!URGENCIES.includes(urgency)) {
    return { ok: false, message: "ระดับความเร่งด่วนไม่ถูกต้อง" };
  }

  if (!process.env.NEXT_PUBLIC_SUPABASE_URL || !process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY) {
    return { ok: true, message: "โหมดสาธิต: ยังไม่ได้ตั้งค่า Supabase จึงไม่ได้บันทึกข้อมูลจริง" };
  }

  const supabase = await createClient();
  const { data: auth } = await supabase.auth.getUser();
  if (!auth.user) {
    return { ok: true, message: "โหมดสาธิต: ยังไม่ได้เข้าสู่ระบบ จึงไม่ได้บันทึกข้อมูลจริง" };
  }

  // Photos were uploaded by the browser into the user's own folder; accept only paths we would have made.
  const ownPath = new RegExp(`^${auth.user.id}/[0-9a-f-]{36}\\.jpg$`);
  if (imagePaths.length > 4 || !imagePaths.every((p) => ownPath.test(p))) {
    return { ok: false, message: "รูปที่แนบไม่ถูกต้อง ลองแนบใหม่อีกครั้ง" };
  }

  // ticket_number is generated by the DB trigger (REQ-YYYYMM-XXXX).
  const { error } = await supabase.from("repair_tickets").insert({
    reporter_id: auth.user.id,
    title,
    description,
    urgency,
    building_id: buildingId,
    location_detail: locationDetail || null,
    image_urls: imagePaths,
    ticket_number: "",
  });
  if (error) return { ok: false, message: `บันทึกไม่สำเร็จ: ${error.message}` };

  revalidatePath("/");
  return { ok: true, message: "ส่งเรื่องแจ้งซ่อมเรียบร้อยแล้ว" };
}
