"use server";

import { revalidatePath } from "next/cache";

import { notifyStaffNewTicket } from "@/lib/push";
import { createClient } from "@/lib/supabase/server";
import type { UrgencyLevel } from "@/types/database";
import { getAuth } from "@/lib/supabase/auth";

const URGENCIES: UrgencyLevel[] = ["low", "medium", "high", "emergency"];

export type ReportResult = { ok: boolean; message: string };

export async function createRepairTicket(
  _prev: ReportResult | null,
  formData: FormData,
): Promise<ReportResult> {
  const str = (k: string) => String(formData.get(k) ?? "").trim();
  const title = str("title");
  // The phone form has one short field; it serves as both the title and the description.
  const description = str("description") || title;
  const buildingId = str("building_id");
  const locationDetail = str("location_detail");
  const urgency = str("urgency") as UrgencyLevel;
  const imagePaths = formData.getAll("image_paths").map(String);
  // Set when the reporter chose to join an open ticket that looked the same.
  const duplicateOf = str("duplicate_of");
  if (duplicateOf && !/^[0-9a-f-]{36}$/i.test(duplicateOf))
    return { ok: false, message: "งานที่เลือกรวมไม่ถูกต้อง" };

  if (!title || !description || !buildingId) {
    return {
      ok: false,
      message: "กรุณากรอกหัวข้อ รายละเอียด และเลือกอาคารให้ครบ",
    };
  }
  if (!URGENCIES.includes(urgency)) {
    return { ok: false, message: "ระดับความเร่งด่วนไม่ถูกต้อง" };
  }

  if (
    !process.env.NEXT_PUBLIC_SUPABASE_URL ||
    !process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
  ) {
    return {
      ok: true,
      message: "โหมดสาธิต: ยังไม่ได้ตั้งค่า Supabase จึงไม่ได้บันทึกข้อมูลจริง",
    };
  }

  const supabase = await createClient();
  const { data: auth } = await getAuth(supabase);
  if (!auth.user) {
    return {
      ok: true,
      message: "โหมดสาธิต: ยังไม่ได้เข้าสู่ระบบ จึงไม่ได้บันทึกข้อมูลจริง",
    };
  }

  // Photos were uploaded by the browser into the user's own folder; accept only paths we would have made.
  const ownPath = new RegExp(`^${auth.user.id}/[0-9a-f-]{36}\\.jpg$`);
  if (imagePaths.length > 4 || !imagePaths.every((p) => ownPath.test(p))) {
    return { ok: false, message: "รูปที่แนบไม่ถูกต้อง ลองแนบใหม่อีกครั้ง" };
  }

  // ticket_number is generated by the DB trigger (REQ-YYYYMM-XXXX).
  const { data: created, error } = await supabase
    .from("repair_tickets")
    .insert({
      reporter_id: auth.user.id,
      title,
      description,
      urgency,
      building_id: buildingId,
      location_detail: locationDetail || null,
      image_urls: imagePaths,
      ticket_number: "",
      duplicate_of: duplicateOf || null,
    })
    .select("id")
    .single();
  if (error) {
    if (duplicateOf)
      return {
        ok: false,
        message: "รวมกับงานนั้นไม่ได้ อาจปิดงานไปแล้ว ลองส่งเป็นงานใหม่",
      };
    return { ok: false, message: `บันทึกไม่สำเร็จ: ${error.message}` };
  }

  // A report merged into an open ticket does not need a second alert for staff.
  if (created && !duplicateOf) {
    const { data: building } = await supabase
      .from("buildings")
      .select("name")
      .eq("id", buildingId)
      .maybeSingle();
    notifyStaffNewTicket({
      id: created.id,
      title,
      place: [building?.name, locationDetail].filter(Boolean).join(" "),
      urgency,
      reporterId: auth.user.id,
    });
  }

  revalidatePath("/");
  return {
    ok: true,
    message: duplicateOf
      ? "รับเรื่องแล้ว รวมกับงานที่มีคนแจ้งไว้ สถานะจะตามงานนั้น"
      : "ส่งเรื่องแจ้งซ่อมเรียบร้อยแล้ว",
  };
}
